baseURL: http://example.org/
languageCode: en-us
theme: github.com/justin-calleja/hugo-theme-terminal
title: My New Hugo Site
enableGitInfo: true

module:
  imports:
    - path: github.com/justin-calleja/days-of-go
    - path: github.com/justin-calleja/hugo-theme-terminal

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 5
    ordered: false
    startLevel: 2

params:
  centerTheme: true
  # contentTypeName: blog
  fullWidthTheme: false
  showMenuItems: 4
  themeColor: green
  showLastUpdated: true

languages:
  en:
    copyright: ''
    keywords: ''
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts
    subtitle: A simple, retro theme for Hugo
    title: Terminal
    params:
      logo:
        logoHomeLink: /
        logoText: Terminal
    menu:
      main:
        - identifier: blog
          name: Blog
          url: /blog
          weight: 10
        - identifier: series
          name: Series
          url: /series
          weight: 20
        - identifier: tips
          name: Tips
          url: /tips
          weight: 30
        - identifier: about
          name: About
          url: /about
          weight: 40

taxonomies:
  tag: tags
